excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- awesomeBeersTests
included:
- awesomeBeers
whitelist_rules:
- empty_count
- force_cast
- force_try
- force_unwrapping
- first_where
- last_where
- legacy_random
- nslocalizedstring_key
- overridden_super_call
- private_over_fileprivate
- redundant_nil_coalescing
- redundant_optional_initialization
- redundant_string_enum_value
- sorted_first_last
- sorted_imports
- statement_position
empty_count: warning
force_cast: error
force_try: error
force_unwrapping: error
first_where: warning
last_where: warning
legacy_random: warning
nslocalizedstring_key: warning
overridden_super_call:
severity: warning
private_over_fileprivate:
severity: warning
redundant_nil_coalescing: warning
redundant_optional_initialization: warning
redundant_string_enum_value: warning
sorted_first_last: warning
sorted_imports: warning
statement_position:
severity: warning
